export const memberdata = [
    {id:1,
    name:"03_Chalisa(Mae) JSD#11",
    picture:"/userProflie/img_001.png",
    text:"UX/UI Designer",
    link:"https://github.com/chalisathanathi",
    facebookLink: "https://www.facebook.com/chalisa.thanathipanont",
    },
    {id:2,
        name:"06_Chanapoom(Poom) JSD#11",
        picture:"/userProflie/img_003.jpg",
        text:"Frontend Developer",
        link:"https://github.com/Karine1412",
        facebookLink: "https://www.facebook.com/poomzaapoom",
    },
    {id:3,
        name:"09_Chutidet(Ice) JSD#11",
        picture:"/userProflie/img_004.png",
        text:"Backend Developer",
        link:"https://github.com/ChutidetBen-oss",
        facebookLink: "https://www.facebook.com/chutidet.benchathamloed"
    },
    {id:4,
        name:"13_Jakkrit(Boat) JSD#11",
        picture:"/userProflie/img_002.png",
        text:"Project Manager",
        link:"https://github.com/boatlittlebear",
        facebookLink: "https://www.facebook.com/profile.php?id=100005841723233"
    },
    {id:5,
        name:"23_Nattha(Game) JSD#11",
        picture:"/userProflie/img_005.jpg",
        text:"Backend Developer",
        link:"https://github.com/nanarnat",
        facebookLink: "https://www.facebook.com/gamenattha"
    },
    {id:6,
        name:"43_Veerakarn(V) JSD#11",
        picture:"/userProflie/img_006.png",
        text:"Frontend Developer",
        link:"https://github.com/veerakarnvrk",
        facebookLink: "https://www.facebook.com/veerakarn.vrk/"
    },
]