export const memberdata = [
    {id:1,
    name:"03_Chalisa(Mae)",
    picture:"/userProflie/img_001.png",
    text:"SEK CODE | JSD 11",
    link:"https://github.com/chalisathanathi",
    facebookLink: "https://www.facebook.com/chalisa.thanathipanont",
    },
    {id:2,
        name:"06_Chanapoom(Poom)",
        picture:"/userProflie/img_003.jpg",
        text:"SEK CODE | JSD 11",
        link:"https://github.com/Karine1412",
        facebookLink: "https://www.facebook.com/poomzaapoom",
    },
    {id:3,
        name:"09_Chutidet(Ice)",
        picture:"/userProflie/img_004.png",
        text:"SEK CODE | JSD 11",
        link:"https://github.com/ChutidetBen-oss",
        facebookLink: "https://www.facebook.com/chutidet.benchathamloed"
    },
    {id:4,
        name:"13_Jakkrit(Boat)",
        picture:"/userProflie/img_002.png",
        text:"SEK CODE | JSD 11",
        link:"https://github.com/boatlittlebear",
        facebookLink: "https://www.facebook.com/profile.php?id=100005841723233"
    },
    {id:5,
        name:"23_Nattha(Game)",
        picture:"/userProflie/Game.png",
        text:"SEK CODE | JSD 11",
        link:"https://github.com/nanarnat",
        facebookLink: "https://www.facebook.com/gamenattha"
    },
    {id:6,
        name:"43_Veerakarn(V)",
        picture:"/userProflie/img_006.png",
        text:"SEK CODE | JSD 11",
        link:"https://github.com/veerakarnvrk",
        facebookLink: "https://www.facebook.com/veerakarn.vrk/"
    },
]