export const readyProducts = [
    {
        _id: "READY_001",
        type: "ready",
        name: "Japanese Green Tea",
        image: "/teaImageData/japanese green tea.png",
        variants: [
            {
                variant_id: "READY_001_M",
                size: "M",
                gram: 50,
                price: 180,
                stock_count: 0,
            },
            {
                variant_id: "READY_001_L",
                size: "L",
                gram: 100,
                price: 340,
                stock_count: 0,
            },
        ],
        is_active: true,
        created_at: "2026-01-15T03:30:00.000Z",
        updated_at: "2026-01-15T03:30:00.000Z",
    },
    {
        _id: "READY_002",
        type: "ready",
        name: "Oolong Tea",
        image: "/teaImageData/brewing-chinese-tea-ceramic-gaiwan-tea-ceremony-closeup.jpg",
        variants: [
            {
                variant_id: "READY_002_M",
                size: "M",
                gram: 50,
                price: 150,
                stock_count: 0,
            },
            {
                variant_id: "READY_002_L",
                size: "L",
                gram: 100,
                price: 280,
                stock_count: 0,
            },
        ],
        is_active: true,
        created_at: "2026-01-15T03:30:00.000Z",
        updated_at: "2026-01-15T03:30:00.000Z",
    },
    {
        _id: "READY_003",
        type: "ready",
        name: "Ceylon Black Tea",
        image: "/teaImageData/ceylon black tea.png",
        variants: [
            {
                variant_id: "READY_003_M",
                size: "M",
                gram: 50,
                price: 130,
                stock_count: 0,
            },
            {
                variant_id: "READY_003_L",
                size: "L",
                gram: 100,
                price: 240,
                stock_count: 0,
            },
        ],
        is_active: true,
        created_at: "2026-01-15T03:30:00.000Z",
        updated_at: "2026-01-15T03:30:00.000Z",
    },
    {
        _id: "READY_004",
        type: "ready",
        name: "Chinese Green Tea",
        image: "/teaImageData/brewing-chinese-tea-ceramic-gaiwan-tea-ceremony-closeup (1).jpg",
        variants: [
            {
                variant_id: "READY_004_M",
                size: "M",
                gram: 50,
                price: 120,
                stock_count: 0,
            },
            {
                variant_id: "READY_004_L",
                size: "L",
                gram: 100,
                price: 220,
                stock_count: 0,
            },
        ],
        is_active: true,
        created_at: "2026-01-15T03:30:00.000Z",
        updated_at: "2026-01-15T03:30:00.000Z",
    },
    {
        _id: "READY_005",
        type: "ready",
        name: "Jasmine Green Tea",
        image: "/teaImageData/jasmine green tea.png",
        variants: [
            {
                variant_id: "READY_005_M",
                size: "M",
                gram: 50,
                price: 160,
                stock_count: 0,
            },
            {
                variant_id: "READY_005_L",
                size: "L",
                gram: 100,
                price: 300,
                stock_count: 0,
            },
        ],
        is_active: true,
        created_at: "2026-01-15T03:30:00.000Z",
        updated_at: "2026-01-15T03:30:00.000Z",
    },
    {
        _id: "READY_006",
        type: "ready",
        name: "Earl Grey Tea",
        image: "/teaImageData/front-view-kettle-with-tea-with-cinnamon-black-tea-dark-background-meal-color-table-morning-coffee-egg-food-breakfast.jpg",
        variants: [
            {
                variant_id: "READY_006_M",
                size: "M",
                gram: 50,
                price: 140,
                stock_count: 0,
            },
            {
                variant_id: "READY_006_L",
                size: "L",
                gram: 100,
                price: 260,
                stock_count: 0,
            },
        ],
        is_active: true,
        created_at: "2026-01-15T03:30:00.000Z",
        updated_at: "2026-01-15T03:30:00.000Z",
    },
    {
        _id: "READY_007",
        type: "ready",
        name: "White Tea",
        image: "/teaImageData/white tea.png",
        variants: [
            {
                variant_id: "READY_007_M",
                size: "M",
                gram: 50,
                price: 200,
                stock_count: 0,
            },
            {
                variant_id: "READY_007_L",
                size: "L",
                gram: 100,
                price: 380,
                stock_count: 0,
            },
        ],
        is_active: true,
        created_at: "2026-01-15T03:30:00.000Z",
        updated_at: "2026-01-15T03:30:00.000Z",
    },
    {
        _id: "READY_008",
        type: "ready",
        name: "Chrysanthemum Tea",
        image: "/teaImageData/chrysanthemum tea.png",
        variants: [
            {
                variant_id: "READY_008_M",
                size: "M",
                gram: 50,
                price: 170,
                stock_count: 0,
            },
            {
                variant_id: "READY_008_L",
                size: "L",
                gram: 100,
                price: 320,
                stock_count: 0,
            },
        ],
        is_active: true,
        created_at: "2026-01-15T03:30:00.000Z",
        updated_at: "2026-01-15T03:30:00.000Z",
    },
    {
        _id: "READY_009",
        type: "ready",
        name: "Chamomile Herbal Tea",
        image: "/teaImageData/wooden-spoons-strainer-near-chamomile-tea.jpg",
        variants: [
            {
                variant_id: "READY_009_M",
                size: "M",
                gram: 30,
                price: 150,
                stock_count: 0,
            },
            {
                variant_id: "READY_009_L",
                size: "L",
                gram: 60,
                price: 280,
                stock_count: 0,
            },
        ],
        is_active: true,
        created_at: "2026-01-15T03:30:00.000Z",
        updated_at: "2026-01-15T03:30:00.000Z",
    },
    {
        _id: "READY_010",
        type: "ready",
        name: "Peppermint Tea",
        image: "/teaImageData/peppermint tea.png",
        variants: [
            {
                variant_id: "READY_010_M",
                size: "M",
                gram: 30,
                price: 140,
                stock_count: 0,
            },
            {
                variant_id: "READY_010_L",
                size: "L",
                gram: 60,
                price: 260,
                stock_count: 0,
            },
        ],
        is_active: true,
        created_at: "2026-01-15T03:30:00.000Z",
        updated_at: "2026-01-15T03:30:00.000Z",
    },
];
