export const members = [
  {
    _id: "1",
    img: "/userProflie/img_001.png",
    userName: "John",
    userLast: "Doe",
    email: "john.doe@example.com",
    phoneNumber: "0812345678",
    address: "123 Sukhumvit Road, Khlong Tan, Bangkok, Thailand",
    role: "user",
    createdAt: "2026-01-01",
  },
  {
    _id: "2",
    img: "/userProflie/img_002.png",
    userName: "Jane",
    userLast: "Smith",
    email: "jane.smith@example.com",
    phoneNumber: "0898765432",
    address: "45 Phahonyothin Road, Chatuchak, Bangkok, Thailand",
    role: "user",
    createdAt: "2026-01-02",
  },
  {
    _id: "3",
    img: "/userProflie/img_003.png",
    userName: "Michael",
    userLast: "Brown",
    email: "michael.brown@example.com",
    phoneNumber: "0823456789",
    address: "78 Suthep, Mueang Chiang Mai, Chiang Mai, Thailand",
    role: "user",
    createdAt: "2026-01-03",
  },
  {
    _id: "4",
    img: "/userProflie/img_004.png",
    userName: "Emily",
    userLast: "Johnson",
    email: "emily.johnson@example.com",
    phoneNumber: "0861122334",
    address: "99 Mittraphap Road, Mueang Khon Kaen, Thailand",
    role: "user",
    createdAt: "2026-01-04",
  },
  {
    _id: "5",
    img: "/userProflie/img_005.png",
    userName: "David",
    userLast: "Wilson",
    email: "david.wilson@example.com",
    phoneNumber: "0849988776",
    address: "12/3 Nimmanhaemin Road, Chiang Mai, Thailand",
    role: "user",
    createdAt: "2026-01-05",
  },
  {
    _id: "6",
    img: "/userProflie/img_006.png",
    userName: "Sophia",
    userLast: "Taylor",
    email: "sophia.taylor@example.com",
    phoneNumber: "0912233445",
    address: "221 Rama 9 Road, Huai Khwang, Bangkok, Thailand",
    role: "user",
    createdAt: "2026-01-06",
  },
  {
    _id: "7",
    img: "/userProflie/img_007.png",
    userName: "Daniel",
    userLast: "Anderson",
    email: "daniel.anderson@example.com",
    phoneNumber: "0935566778",
    address: "56 Srinakarin Road, Bang Na, Bangkok, Thailand",
    role: "user",
    createdAt: "2026-01-07",
  },
  {
    _id: "8",
    img: "/userProflie/img_008.png",
    userName: "Olivia",
    userLast: "Martinez",
    email: "olivia.martinez@example.com",
    phoneNumber: "0956677889",
    address: "18 Sukhumvit Road, Si Racha, Chonburi, Thailand",
    role: "user",
    createdAt: "2026-01-08",
  },
  {
    _id: "9",
    img: "/userProflie/img_009.png",
    userName: "James",
    userLast: "Lee",
    email: "james.lee@example.com",
    phoneNumber: "0883344556",
    address: "90 Pracha Uthit Road, Thung Khru, Bangkok, Thailand",
    role: "user",
    createdAt: "2026-01-09",
  },
  {
    _id: "10",
    img: "/userProflie/img_011.png",
    userName: "Emma",
    userLast: "Clark",
    email: "emma.clark@example.com",
    phoneNumber: "0817788990",
    address: "7/1 Khlong Song Road, Khlong Sam Wa, Bangkok, Thailand",
    role: "user",
    createdAt: "2026-01-10",
  },
];
